dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=commons setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: PZcNObGQ0xDLzV8dL7gwJK3UnTfvlNP+g8nY6YYwY6lxvLRtHDLW4XVZ83EPQG0Ags7Wrx9SB6YyyYwJ0cuZ3FiFC2kRrcDfAV/ZcmTHfdaqXUFYsIg20zY0nl06n2ACXFdAJCfpFPgmJRWFrAgKiLh7fQC/vo6lS+IERQXrl0aVCrxMzcmC5ru7wN+Txaz45gokT1v6mqnXfD6XqOgdEkUzD+11j01F2M/UXw8EXvztq04VDKMhb0IOYglbp09nAQ8S2CEkhLPgdFauEG5ZemHN2ilMVue4qi+AB5vL9pohTVX6UhK1hW+qaP6SBepvP+VbXDnxb4Ie+gAQfQ6p/PYKwmJdYLhySD2BJ0ksF1OXu0WXc1Cx97NOPrMGk7f21RhRebCCKnZEw5tzDLfPbg0RAbtzLjKGMX+ZEWkSKOIlzmuZPPMGP/3eqJGblL17fh3MRMiN3xcMPxwlQKg1m/c0D9MoVv15D+fjmT6hXje0/O6hLkbhIQMz3wEcRZJHeMFrQquE/2NHhfFHjpXCGb+u0rdIMQB1UgNQZxSnd54maqNRSi9K117Shsdhpj0LVZUDTwUvb94UmkpfY1zogsxWg46pNikmYcAmFHGMpKmXZXJnTPARqmkzpFpTNTuAR+C9dqgqHnapQxvY6sQRJojleIkVgWMmugASDZyHOVg=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
